name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        env:
          JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          TELEGRAM_BOT_USERNAME: ${{ secrets.TELEGRAM_BOT_USERNAME }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_SUCCESS_URL: ${{ secrets.STRIPE_SUCCESS_URL }}
          STRIPE_CANCEL_URL: ${{ secrets.STRIPE_CANCEL_URL }}
        run: mvn --batch-mode --update-snapshots verify
